### ISSUE TITLE
brush().touchable not a function

### ISSUE THREAD

**Issue by japrescott** [d3/d3-brush#63] opened 2019-11-20 13:46 UTC
I am trying to override the touch detector to disable the brush on touch enabled devices.
when setting up the brush, I get an error that `touchable` is not a function

				brush = d3.brushX()
					.touchable(()=>{ // <-- throws error
						return false;
					})
					.filter(()=>{
						return !d3.event.shiftKey;
					})
					.extent([[0, 0], [width, height]])
					.on("start", () => {
						console.log('brush started');
					})

looking at the sourcecode doesn't seem to correlate with the information provided in the Readme. Is this a relic of the past or will this be exposed in the future?

**Comment by mbostock** [comment] 2019-11-20 15:27
It looks like the touchable logic was implemented internally, but the *brush*.touchable accessor wasn’t exposed as intended. [*brush*.touchable](https://github.com/d3/d3-brush#brush_touchable) was intended to be added in [d3-brush 1.1.0](https://github.com/d3/d3-brush/releases/tag/v1.1.0) ([d3 5.10.0](https://github.com/d3/d3/releases/tag/v5.10.0)).

**Comment by mbostock** [comment] 2019-11-20 15:31
Fixed in [1.1.5](https://github.com/d3/d3-brush/releases/tag/v1.1.5).

**Closed by mbostock** 2019-11-20 15:31 UTC
