### ISSUE TITLE
Brush loses functionality if mouseup occurs outside frame

### ISSUE THREAD

**Issue by rbwest** [d3/d3-brush#39] opened 2018-11-09 14:50 UTC
Typically clicking on a brush context results creates an "end" event with a null selection. When these conditions are seen the brush can be re-initialized to the entire range of the context area as is done in [this example](https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172).

If a brush event is started but the user releases the mouse outside of the frame, then the brush event will still be going on when the user mouses back into the frame. The user then must click to end the brush event, but in doing so the brush selection rect disappears. 

At this point clicking the brush context will no longer create an "end" event with a null selection to reset the brush selection to the entire range of the context area.

**Comment by mbostock** [comment] 2019-08-02 20:10
Thanks for the report. This sounds like a duplicate of #18, plus the general weirdness of how events work in the context of frames. For the latter, see https://github.com/d3/d3-drag/issues/9 for discussion.

**Closed by mbostock** 2019-08-02 20:10 UTC
